### PR TITLE
Worker shutdown handling

### LINKED ISSUE #98: Worker process fails to handle termination signals reliably
**Description:**

The `rspecq` worker process is responsible for both executing tests and handling signals (e.g., `SIGTERM`, `SIGINT`) for graceful shutdown. This dual responsibility leads to unreliable behavior, particularly in CI environments with volatile workers. We are seeing this problem in EKS, using spot instances that are eventually revoked from kubernetes.

**Problem:**

When a worker process is executing RSpec tests, it has loaded the entire application environment. This environment may include third-party gems or application code that installs its own signal handlers, traps signals, or performs non-interruptible operations.

As a result, there is no guarantee that a signal sent to the worker process will be handled correctly or in a timely manner. The signal may be ignored, swallowed, or lead to a crash, preventing the worker from shutting down gracefully. More importantly, if the signalis handled by rspec it might lead to false-negative build results.

We could sent SIGKILL to avoid the above consequences, but in that case, the queue will be left in non-optimal state.

**Consequences:**

This has a significant negative impact on CI stability:

**Orphaned Jobs:** When a worker is forcefully killed without shutting down gracefully, the job it had reserved in Redis remains locked until the relevant timeout is reached, increasing build times significantly.

**Proposed Solution:**

To solve this, we should isolate signal handling from test execution by introducing a dedicated **Supervisor process**.

This architectural change involves:

1.  A lightweight **Supervisor** process whose only responsibility is to fork and monitor a worker. Since it doesn't load any application code, it can handle OS signals reliably.
2.  Upon receiving a signal, the supervisor notifies the worker to shut down using a simple and robust IPC mechanism (e.g., an io pipe pair).
3.  The **Worker** process no longer needs to handle signals directly. It only needs to periodically check the IPC mechanism to see if a shutdown has been requested.

### PR DESCRIPTION
**Pull request by ctrochalakis**
Closes #98

### CODE REVIEW

File: lib/rspecq/supervisor.rb [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+      @shutdown
+    end
+
+    def graceful_shutdown_sent?
+      @graceful_shutdown_sent
+    end
+
+    def sigkill_shutdown_sent?
+      @sigkill_shutdown_sent
+    end
```
Comment (iridakos) [inline lib/rspecq/supervisor.rb:76]: Are these two needed?

File: lib/rspecq/supervisor.rb [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+    attr_reader :graceful_shutdown_signal
+
+    def initialize(graceful_shutdown_timeout: nil, graceful_shutdown_signal: nil, worker_opts: {})
+      @shutdown = false
+      @shutdown_initiated_at = nil
+
+      @graceful_shutdown_signal = graceful_shutdown_signal
+      @graceful_shutdown_timeout = graceful_shutdown_timeout
+      @graceful_shutdown_sent = false
+      @sigkill_shutdown_sent = false
```
Comment (iridakos) [inline lib/rspecq/supervisor.rb:40]: Is this one used anywhere?

File: lib/rspecq/supervisor.rb (hunk 1 above)
Comment (ctrochalakis) [reply lib/rspecq/supervisor.rb:76]: yes, fixing them. We should check them to only send shutdown sequence signals once.
